### ISSUE TITLE
作者加油，修理VIP金币回扣辛苦了

### ISSUE THREAD

**Issue by ya01232** [seagulltool/seagulltool.github.io#4]
虽然我只是一个普普通通的用户，没什么帮得到忙。但是打心底佩服您的付出。特别是在不收费情况下。顺便好奇一下只靠谷歌广告，应该能收回节点的成本吧（更好奇能获利多少辛苦费）
我只是一个普普通通的高中生，买不起vpn。最后，真心祝愿bug早日修复。（当初发现旧版本用不了了还以为vpn凉了.....然后上这更新了还能用）

**Comment by seagulltool** [comment]
thanks for your support!
