### ISSUE TITLE
关于6.5.3的一个小问题

### ISSUE THREAD

**Issue by SunLC258** [seagulltool/seagulltool.github.io#5]
首先感谢作者大大的奉献，以下是我在使用6.5.3时出现的一些小问题
在我的手机上6.5.3不仅是出现了金币清零的情况，还出现了闪退的情况，只有重启手机才能短暂打开应用，每次打开应用都像是重新下载了似的，会弹出在第一次使用前的提示。
我的手机系统是鸿蒙4.0.0.165，不知道是不是和这个有关系。

**Comment by seagulltool** [comment]
应该是同一个原因导致的，请使用最新的6.5.4修复版本试试，谢谢反馈！
