### ISSUE TITLE
6.5.3版本部分手机还是有问题

### ISSUE THREAD

**Issue by HatOGblack** [seagulltool/seagulltool.github.io#6]
我用的IQOO就不行,Origin OS 4 安卓版本14 ,备用机Realme就没问题,Realme的安卓本是11

**Comment by seagulltool** [comment]
感谢你的反馈，目前已经确定是部分机型的高版本安卓系统功能被厂商修改导致的问题，请在有问题的机器上上使用最新的6.5.4验证一下，理论上应该修复了！
