### ISSUE TITLE
6.6版本的问题

### ISSUE THREAD

**Issue by lumine114514520** [seagulltool/seagulltool.github.io#7]
最新版本，出现了以前安卓14打不开的问题，请问能够修复吗，作者大大

**Comment by lumine114514520** [comment]
我的iqoo，橘子4，112版本

**Comment by seagulltool** [comment]
working on the investigation....thanks

**Comment by seagulltool** [comment]
经部分用户验证，6.6.1可以正常使用不闪退，这个版本不满足Google对安卓14的要求，所以无法上架Google Play。请自行到官网下载安装包。 @lumine114514520
